### ISSUE TITLE
Y2010 file getAbbreviatedName null pointer exception

### ISSUE THREAD

**Issue by patricknee** [USPTO/PatentPublicData#13]
Splitting out earlier post with multiple error types:

Running Y2010 file ipg100105.zip, to limit. Error follows:

```
patrick$ java -cp PatentDocument/target/*:PatentDocument/target/dependency-jars/*:resources gov.uspto.patent.TransformerCli --input="BulkDownloader/download/grants/2010/ipg100105.zip" --outBulk=false --outdir="BulkDownloader/download/grants/2010/expanded/"
2016-11-08 21:51:36,523 INFO  [main] TransformerCli - --- Start ---
2016-11-08 21:51:36,560 INFO  [main] TransformerCli - Dump File[1]: /Users/patrick/dev/repos/PatentPublicData/BulkDownloader/download/grants/2010/ipg100105.zip
2016-11-08 21:51:36,562 INFO  [main] PatentDocFormatDetect - PatentDocFormat fromFileName: RedbookGrant
2016-11-08 21:51:36,569 INFO  [main] ZipReader - Reading zip file: /Users/patrick/dev/repos/PatentPublicData/BulkDownloader/download/grants/2010/ipg100105.zip
2016-11-08 21:51:36,601 INFO  [main] ZipReader - Found 1 file[FileFilter [matchRules=[SuffixFilter [suffixes=[xml]]]]]: ipg100105.xml
2016-11-08 21:51:36,604 INFO  [main] PatentDocFormatDetect - PatentType fromContent: RedbookGrant
2016-11-08 21:51:37,205 INFO  [main] TransformerCli - Record: 'USD0607176S1' from /Users/patrick/dev/repos/PatentPublicData/BulkDownloader/download/grants/2010/ipg100105.zip:1
2016-11-08 21:51:37,351 INFO  [main] TransformerCli - Record: 'USD0607177S1' from /Users/patrick/dev/repos/PatentPublicData/BulkDownloader/download/grants/2010/ipg100105.zip:2
2016-11-08 21:51:37,463 INFO  [main] TransformerCli - Record: 'USD0607178S1' from /Users/patrick/dev/repos/PatentPublicData/BulkDownloader/download/grants/2010/ipg100105.zip:3
2016-11-08 21:51:37,601 INFO  [main] TransformerCli - Record: 'USD0607179S1' from /Users/patrick/dev/repos/PatentPublicData/BulkDownloader/download/grants/2010/ipg100105.zip:4
2016-11-08 21:51:37,738 INFO  [main] TransformerCli - Record: 'USD0607180S1' from /Users/patrick/dev/repos/PatentPublicData/BulkDownloader/download/grants/2010/ipg100105.zip:5

.......(trimmed)
2016-11-08 21:55:32,444 INFO  [main] TransformerCli - Record: 'US7642067B2' from /Users/patrick/dev/repos/PatentPublicData/BulkDownloader/download/grants/2010/ipg100105.zip:1937
2016-11-08 21:55:32,555 INFO  [main] TransformerCli - Record: 'US7642068B2' from /Users/patrick/dev/repos/PatentPublicData/BulkDownloader/download/grants/2010/ipg100105.zip:1938
2016-11-08 21:55:32,618 INFO  [main] TransformerCli - Record: 'US7642069B2' from /Users/patrick/dev/repos/PatentPublicData/BulkDownloader/download/grants/2010/ipg100105.zip:1939
Exception in thread "main" java.lang.NullPointerException
	at gov.uspto.patent.model.entity.NamePerson.getAbbreviatedName(NamePerson.java:75)
	at gov.uspto.patent.serialize.JsonMapper.mapName(JsonMapper.java:370)
	at gov.uspto.patent.serialize.JsonMapper.mapApplicant(JsonMapper.java:306)
	at gov.uspto.patent.serialize.JsonMapper.buildJson(JsonMapper.java:99)
	at gov.uspto.patent.serialize.JsonMapper.write(JsonMapper.java:68)
	at gov.uspto.patent.serialize.JsonMapper.write(JsonMapper.java:56)
	at gov.uspto.patent.TransformerCli.write(TransformerCli.java:203)
	at gov.uspto.patent.TransformerCli.processDumpFile(TransformerCli.java:188)
	at gov.uspto.patent.TransformerCli.process(TransformerCli.java:116)
	at gov.uspto.patent.TransformerCli.main(TransformerCli.java:276)
```

**Comment by patricknee** [comment]
Put try/catch in NamePerson.getAbbreviatedName:

Also added LOGGER references to allow reporting the error.

This loses any first name information, but allows processing to proceed.

Examples showing up in the log appear to be blank text first names (firstName=" "), but I haven't looked further.

    ```
public String getAbbreviatedName() {
        if (Strings.isNullOrEmpty(firstName)) {
            try
            {
                return lastName + ", " + firstName.substring(0, 1) + '.';
            }
            catch (Exception e)
            {
                LOGGER.warn("Error parsing in getAbbreviatedName, firstName={} ", firstName, e);
                return lastName;
            }
        } else {
            return lastName;
        }
    }
```

**Comment by bgfeldm** [comment]
Checked in fix for NullPointerException.  If statement should have been checking if NOT null or empty.  The bad logic was also causing the method to only return the last name.  A unit test was also created. 

Thanks you for pointing this out,
Brian
