### ISSUE TITLE
getting test failure 'readSamples(gov.uspto.patent.doc.greenbook.GreenbookTest): No match available' on maven clean install

### ISSUE THREAD

**Issue by diego-** [USPTO/PatentPublicData#15]
When I run: `mvn clean install` on the top level PatentPublicData directory, I get the following failure:

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running gov.uspto.document.model.classification.cpc.CpCClassificationTest
[0/D, 1/D/D07, 2/D/D07/D07B, 3/D/D07/D07B/D07B2201, 4/D/D07/D07B/D07B2201/D07B22012051]
Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.08 sec
Running gov.uspto.document.model.classification.ipc.IpcClassificationTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec
Running gov.uspto.document.model.classification.uspc.UspcClassificationTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.063 sec
Running gov.uspto.document.model.DocumentIdTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.116 sec
Running gov.uspto.document.parser.dom4j.PatentParserTest
2016-11-20 10:29:17,191 WARN  [       main] UNDEFINED1234567     AbstractTextNode - Patent does not have an Abstract.
2016-11-20 10:29:17,193 WARN  [       main] UNDEFINED1234567     DescriptionNode - Patent does not have a Description.
2016-11-20 10:29:17,232 WARN  [       main] UNDEFINED1234567     DescriptionNode - Patent does not have a Description.
2016-11-20 10:29:17,246 WARN  [       main] US7654321            AbstractTextNode - Patent does not have an Abstract
2016-11-20 10:29:17,247 WARN  [       main] US7654321            DescriptionNode - Patent does not have a Description.
2016-11-20 10:29:17,255 WARN  [       main] UNDEFINED1234567     DescriptionNode - Patent does not have a Description.
2016-11-20 10:29:17,260 WARN  [       main] UNDEFINED1234567     DocumentIdNode - Invalid document-id can not be Null.
2016-11-20 10:29:17,261 WARN  [       main] UNDEFINED1234567     ApplicationIdNode - Invalid document-id can not be Null.
2016-11-20 10:29:17,266 WARN  [       main] UNDEFINED1234567     AbstractTextNode - Patent does not have an Abstract
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.336 sec
Running gov.uspto.patent.doc.greenbook.FormattedTextTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.005 sec
Running gov.uspto.patent.doc.greenbook.GreenbookTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.067 sec <<< FAILURE!
readSamples(gov.uspto.patent.doc.greenbook.GreenbookTest)  Time elapsed: 0.067 sec  <<< ERROR!
java.lang.IllegalStateException: No match available
	at java.util.regex.Matcher.end(Matcher.java:415)
	at gov.uspto.patent.doc.greenbook.items.DescriptionFigures.findFigures(DescriptionFigures.java:61)
	at gov.uspto.patent.doc.greenbook.items.DescriptionFigures.read(DescriptionFigures.java:40)
	at gov.uspto.patent.doc.greenbook.fragments.DescriptionNode.read(DescriptionNode.java:42)
	at gov.uspto.patent.doc.greenbook.Greenbook.parse(Greenbook.java:113)
	at gov.uspto.parser.dom4j.keyvalue.KvParser.parse(KvParser.java:37)
	at gov.uspto.parser.dom4j.keyvalue.KvParser.parse(KvParser.java:30)
	at gov.uspto.patent.doc.greenbook.GreenbookTest.readSamples(GreenbookTest.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Running gov.uspto.patent.doc.greenbook.items.DescriptionFiguresTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running gov.uspto.patent.doc.pap.PatentAppPubParserTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.257 sec
Running gov.uspto.patent.doc.sgml.SgmlTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.166 sec
Running gov.uspto.patent.doc.xml.ApplicationParserTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.282 sec
Running gov.uspto.patent.doc.xml.FormattedTextTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.018 sec
Running gov.uspto.patent.doc.xml.GrantParserTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.025 sec
Running gov.uspto.patent.mathml.MathMLTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec
Running gov.uspto.patent.model.entity.NamePersonTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec
Running gov.uspto.patent.serialize.JsonMapperTest
{"patentCorpus":"PGPUB","patentType":"UTILITY","productionDate":{"raw":"20160101","iso":"2016-01-01T00:00:00Z"},"publishedDate":{"raw":"20160202","iso":"2016-02-02T00:00:00Z"},"documentId":"US123456789","documentDate":{"raw":"","iso":""},"applicationId":"","applicationDate":{"raw":"","iso":""},"relatedIds":[],"otherIds":[],"agent":[],"applicant":[],"inventors":[{"sequence":"","name":{"type":"person","raw":"Inventee, Bob","prefix":"","firstName":"Bob","middleName":"","lastName":"Inventee","suffix":"","abbreviated":"Inventee, B.","synonyms":[]},"address":{"street":"123 Main St","city":"Alexandria","state":"VA","zipCode":"22314","country":"US","email":"","fax":"","phone":""},"residency":"","nationality":""}],"assignees":[{"name":{"type":"org","raw":"Inventee Inc.","suffix":"","synonyms":[]},"address":{"street":"123 Main St","city":"Alexandria","state":"VA","zipCode":"22314","country":"US","email":"","fax":"","phone":""},"role":"","roleDefinition":""}],"examiners":[],"title":"Test Patent","abstract":{"raw":"This is the Abstract Section.","normalized":"   This is the Abstract Section. \n","plain":"   This is the Abstract Section. \n"},"description":{"full_raw":"Drawing Desc Text\nRell App Desc Text\nBrief Summar Desc Text\nDetailed Description Text\n","REL_APP_DESC":{"raw":"Rell App Desc Text","normalized":"   Rell App Desc Text \n","plain":"   Rell App Desc Text \n"},"DRAWING_DESC":{"raw":"Drawing Desc Text","normalized":"   Drawing Desc Text \n","plain":"   Drawing Desc Text \n"},"BRIEF_SUMMARY":{"raw":"Brief Summar Desc Text","normalized":"   Brief Summar Desc Text \n","plain":"   Brief Summar Desc Text \n"},"DETAILED_DESC":{"raw":"Detailed Description Text","normalized":"   Detailed Description Text \n","plain":"   Detailed Description Text \n"}},"claims":[],"citations":[],"classification":{"ipc":[],"uspc":[],"cpc":[]}}
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.026 sec

Results :

Tests in error: 
  readSamples(gov.uspto.patent.doc.greenbook.GreenbookTest): No match available

Tests run: 51, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] PatentPublicData ................................... SUCCESS [ 19.928 s]
[INFO] Common ............................................. SUCCESS [  7.860 s]
[INFO] PatentDocument ..................................... FAILURE [  6.423 s]
[INFO] BulkDownloader ..................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 34.324 s
[INFO] Finished at: 2016-11-20T10:29:21-05:00
[INFO] Final Memory: 34M/524M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project PatentDocument: There are test failures.
```

Do you have any advice for how to correct?

**Comment by bgfeldm** [comment]
Fixed and code has been checked in.
