### ISSUE TITLE
getting some test failures for PatentDocument on 'maven clean install'

### ISSUE THREAD

**Issue by diego-** [USPTO/PatentPublicData#16]
updated local repo to latest master (75597ea) and run `mvn clean install`, getting test failures on PatentDocument below:

```
 T E S T S
-------------------------------------------------------
Running gov.uspto.document.model.classification.CpCClassificationTest
[0/D, 1/D/D07, 2/D/D07/D07B, 3/D/D07/D07B/D07B2201, 4/D/D07/D07B/D07B2201/D07B22012051]
Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.072 sec
Running gov.uspto.document.model.classification.IpcClassificationTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec
Running gov.uspto.document.model.classification.UspcClassificationTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.051 sec
Running gov.uspto.document.model.DocumentIdTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.097 sec
Running gov.uspto.document.parser.dom4j.PatentParserTest
2016-12-01 13:37:31,065 WARN  [       main] UNDEFINED1234567     AbstractTextNode - Patent does not have an Abstract.
2016-12-01 13:37:31,069 WARN  [       main] UNDEFINED1234567     DescriptionNode - Patent does not have a Description.
2016-12-01 13:37:31,100 WARN  [       main] UNDEFINED1234567     DescriptionNode - Patent does not have a Description.
2016-12-01 13:37:31,118 WARN  [       main] US7654321            AbstractTextNode - Patent does not have an Abstract
2016-12-01 13:37:31,118 WARN  [       main] US7654321            DescriptionNode - Patent does not have a Description.
2016-12-01 13:37:31,128 WARN  [       main] UNDEFINED1234567     DescriptionNode - Patent does not have a Description.
2016-12-01 13:37:31,137 WARN  [       main] US3930584            ApplicationIdNode - Invalid document-id can not be Null.
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.296 sec
Running gov.uspto.patent.doc.greenbook.FormattedTextTest
Tests run: 3, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0.009 sec <<< FAILURE!
normalizedSimpleHtml(gov.uspto.patent.doc.greenbook.FormattedTextTest)  Time elapsed: 0.007 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<...2>SECTION TITLE</h2>[ 
<p>Paragraph text, referenceing <a class="figref">FIG. 1</a> is a side elevational view</p> 
<p>More text now referenceing <a class="figref">FIG. 2B</a> is a top view</p>]> but was:<...2>SECTION TITLE</h2>[
<p>Paragraph text, referenceing <a class="figref">FIG. 1</a> is a side elevational view</p>
<p>More text now referenceing <a class="figref">FIG. 2B</a> is a top view</p>
]>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at gov.uspto.patent.doc.greenbook.FormattedTextTest.normalizedSimpleHtml(FormattedTextTest.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

createRefs(gov.uspto.patent.doc.greenbook.FormattedTextTest)  Time elapsed: 0.001 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<...ss="figref">FIG. 1(a[)</a>] is> but was:<...ss="figref">FIG. 1(a[</a>)] is>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at gov.uspto.patent.doc.greenbook.FormattedTextTest.createRefs(FormattedTextTest.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Running gov.uspto.patent.doc.greenbook.GreenbookTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.096 sec
Running gov.uspto.patent.doc.greenbook.items.DescriptionFiguresTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec
Running gov.uspto.patent.doc.pap.PatentAppPubParserTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.206 sec
Running gov.uspto.patent.doc.sgml.SgmlTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.147 sec
Running gov.uspto.patent.doc.xml.ApplicationParserTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.225 sec
Running gov.uspto.patent.doc.xml.FormattedTextTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.01 sec
Running gov.uspto.patent.doc.xml.GrantParserTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.548 sec
Running gov.uspto.patent.mathml.MathMLTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 sec
Running gov.uspto.patent.model.entity.NamePersonTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec
Running gov.uspto.patent.serialize.JsonMapperTest
{"patentCorpus":"PGPUB","patentType":"UTILITY","productionDate":{"raw":"20160101","iso":"2016-01-01T00:00:00Z"},"publishedDate":{"raw":"20160202","iso":"2016-02-02T00:00:00Z"},"documentId":"US123456789","documentDate":{"raw":"","iso":""},"applicationId":"","applicationDate":{"raw":"","iso":""},"relatedIds":[],"otherIds":[],"agent":[],"applicant":[],"inventors":[{"sequence":"","name":{"type":"person","raw":"Inventee, Bob","prefix":"","firstName":"Bob","middleName":"","lastName":"Inventee","suffix":"","abbreviated":"Inventee, B.","synonyms":[]},"address":{"street":"123 Main St","city":"Alexandria","state":"VA","zipCode":"22314","country":"US","email":"","fax":"","phone":""},"residency":"","nationality":""}],"assignees":[{"name":{"type":"org","raw":"Inventee Inc.","suffix":"","synonyms":[]},"address":{"street":"123 Main St","city":"Alexandria","state":"VA","zipCode":"22314","country":"US","email":"","fax":"","phone":""},"role":"","roleDefinition":""}],"examiners":[],"title":"Test Patent","abstract":{"raw":"This is the Abstract Section.","normalized":"   This is the Abstract Section. \n","plain":" This is the Abstract Section. "},"description":{"full_raw":"Drawing Desc Text\nRell App Desc Text\nBrief Summar Desc Text\nDetailed Description Text\n","REL_APP_DESC":{"raw":"Rell App Desc Text","normalized":"   Rell App Desc Text \n","plain":" Rell App Desc Text "},"DRAWING_DESC":{"raw":"Drawing Desc Text","normalized":"   Drawing Desc Text \n","plain":" Drawing Desc Text "},"BRIEF_SUMMARY":{"raw":"Brief Summar Desc Text","normalized":"   Brief Summar Desc Text \n","plain":" Brief Summar Desc Text "},"DETAILED_DESC":{"raw":"Detailed Description Text","normalized":"   Detailed Description Text \n","plain":" Detailed Description Text "}},"claims":[],"citations":[],"classification":{"ipc":[],"uspc":[],"cpc":[]}}
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.024 sec
Running gov.uspto.patent.validate.AbstractRuleTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec
Running gov.uspto.patent.validate.ClaimRuleTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 sec
Running gov.uspto.patent.validate.ClassificationRuleTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec
Running gov.uspto.patent.validate.DescriptionRuleTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 sec
Running gov.uspto.patent.validate.TitleRuleTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec

Results :

Failed tests:   normalizedSimpleHtml(gov.uspto.patent.doc.greenbook.FormattedTextTest): expected:<...2>SECTION TITLE</h2>[ (..)
  createRefs(gov.uspto.patent.doc.greenbook.FormattedTextTest): expected:<...ss="figref">FIG. 1(a[)</a>] is> but was:<...ss="figref">FIG. 1(a[</a>)] is>

Tests run: 67, Failures: 2, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] PatentPublicData ................................... SUCCESS [  3.146 s]
[INFO] Common ............................................. SUCCESS [  2.813 s]
[INFO] PatentDocument ..................................... FAILURE [  5.830 s]
[INFO] BulkDownloader ..................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11.939 s
[INFO] Finished at: 2016-12-01T13:37:34-05:00
[INFO] Final Memory: 32M/385M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project PatentDocument: There are test failures.
[ERROR] 
```

**Comment by bgfeldm** [comment]
Sorry about that.  I really need to run the unit test more often, especially before checkin.

I update the unit test to reflect changes I made when transforming the formatted patent text into a unified simple html format.

Thanks again,

Brian
