### ISSUE TITLE
SAX error 2001 Application

### ISSUE THREAD

**Issue by patricknee** [USPTO/PatentPublicData#22]
TransformerCli on 2001 application file pa010322.zip and 2002 application file pa020103.zip:

The following fatal error occurs:

```
2017-01-08 09:22:17,666 ERROR [       main] pa010322.zip         TransformerCli - Patent Reader error: 
gov.uspto.patent.PatentReaderException: Failed to load XML
	at gov.uspto.patent.PatentReader.getJDOM(PatentReader.java:94)
	at gov.uspto.patent.PatentReader.read(PatentReader.java:75)
	at gov.uspto.patent.TransformerCli.processDumpFile(TransformerCli.java:167)
	at gov.uspto.patent.TransformerCli.process(TransformerCli.java:116)
	at gov.uspto.patent.TransformerCli.main(TransformerCli.java:277)
Caused by: org.dom4j.DocumentException: Error on line 372 of document  : The entity "ldquo" was referenced, but not declared. Nested exception: The entity "ldquo" was referenced, but not declared.
	at org.dom4j.io.SAXReader.read(SAXReader.java:482)
	at org.dom4j.io.SAXReader.read(SAXReader.java:365)
	at gov.uspto.patent.PatentReader.getJDOM(PatentReader.java:92)
	... 4 more
```

**Comment by bgfeldm** [comment]
A while back to get around this I added the method addHTMLEntities() to the DumpFileXml class which which adds html-entities.dtd to the XML before reading.   Many of the CLI tools like Look and ExtractPatent has a command-line option to addHtmlEntities.  But the TransformerCli does not, I will look into adding this option to the TransformerCli. If I can get around to fix it quickly I will push an update today.

**Comment by patricknee** [comment]
To be clear, I am just trying to process the applications to the bulk JSON file as I do with grants (gov.uspto.patent.TransformerCli --input="ipa_corpusApps_2005.zip" --outBulk=false") and it crashes with applications. I don't need any new interfaces. I am not sure whether that makes the bug report clearer; your note about adding a new option to TransformerCli isn't immediately clear to me...

**Comment by bgfeldm** [comment]
The issue exists with the PAP xml which as provided is invalid xml, since it fails to include HTML entities.  To get around the issue the software adds DTD decoration at the top of the xml.

But the solution which is not currently included within the TransformerCli, is also broken for the other tools. But a single fix should be able to fix them all.

With the fix I am aiming to ke the command-line option optional,  If it correctly identifies the application as a PAP it will add the html entities.

**Comment by bgfeldm** [comment]
Fix checked in.
