### ISSUE TITLE
TransformerCli throws NoSuchElementException while processing pg010102.zip

### ISSUE THREAD

**Issue by pedagogly** [USPTO/PatentPublicData#26]
````
2017-01-10 17:08:20,011 INFO  [main] TransformerCli - --- Start ---
2017-01-10 17:08:20,041 INFO  [main] TransformerCli - Dump File[1]: pg010102.zip
2017-01-10 17:08:20,043 INFO  [main] PatentDocFormatDetect - PatentDocFormat fromFileName: Sgml
2017-01-10 17:08:20,046 INFO  [main] ZipReader - Reading zip pg010102.zip
Exception in thread "main" java.util.NoSuchElementException
	at gov.uspto.common.file.archive.ZipReader.next(ZipReader.java:122)
	at gov.uspto.patent.bulk.DumpFile.open(DumpFile.java:65)
	at gov.uspto.patent.bulk.DumpFileXml.open(DumpFileXml.java:31)
	at gov.uspto.patent.TransformerCli.processDumpFile(TransformerCli.java:166)
	at gov.uspto.patent.TransformerCli.process(TransformerCli.java:122)
	at gov.uspto.patent.TransformerCli.main(TransformerCli.java:296)
````

**Comment by bgfeldm** [comment]
Reason for the error: the ZipReader is looking an internal file with suffix of XML, but instead the file ends in SGML

I will update the code to look for XML and SGML files.

**Comment by bgfeldm** [comment]
After fixing the issue, I have found another issue the document has unclosed CITED-BY-EXAMINER and CITED-BY-OTHER tags.

**Comment by pedagogly** [comment]
Thanks Brian.

**Comment by bgfeldm** [comment]
Added Fix to close any unclosed tags.

**Comment by pedagogly** [comment]
Commit 7d8b3fc is not building:
```
gov/uspto/patent/PatentReader.java:[12,24] cannot find symbol
  symbol:   class ParseSettings
  location: package org.jsoup.parser
gov/uspto/patent/PatentReader.java:[116,61] cannot find symbol
  symbol:   variable ParseSettings
  location: class gov.uspto.patent.PatentReader
2 errors 

```

**Comment by bgfeldm** [comment]
Just checked in updated pom with new version of JSoup.

**Comment by pedagogly** [comment]
Thank that fixed the compile step, but a test is failing:

```
-------------------------------------------------------------------------------
Test set: gov.uspto.document.parser.dom4j.PatentParserTest
-------------------------------------------------------------------------------
Tests run: 6, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.402 sec <<< FAILURE!
parseFailUnknownXMLType(gov.uspto.document.parser.dom4j.PatentParserTest)  Time elapsed: 0.075 sec  <<< ERROR!
java.lang.Exception: Unexpected exception, expected<gov.uspto.patent.PatentReaderException> but was<java.lang.NullPointerException>
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:28)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:53)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:123)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
Caused by: java.lang.NullPointerException
	at gov.uspto.patent.doc.pap.PatentAppPubParser.parse(PatentAppPubParser.java:67)
	at gov.uspto.patent.PatentReader.read(PatentReader.java:78)
	at gov.uspto.document.parser.dom4j.PatentParserTest.parseFailUnknownXMLType(PatentParserTest.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)
	... 21 more
```

**Comment by bgfeldm** [comment]
The JUnit test has been removed.  

The test case check for an exception which was being triggered by unclosed tag. but since unclosed tags are now fixed the test case is no longer needed.

Thanks
