### ISSUE TITLE
TransformerCli throws NumberFormatException while processing pftaps19760309_wk10.zip

### ISSUE THREAD

**Issue by pedagogly** [USPTO/PatentPublicData#27]
The stack trace is as follows (the exception stops processing of the remaining documents in the archive):

```
Exception in thread "main" java.lang.NumberFormatException: null
	at java.lang.Integer.parseInt(Integer.java:542)
	at java.lang.Integer.valueOf(Integer.java:766)
	at gov.uspto.patent.model.classification.IpcClassification.standardize(IpcClassification.java:121)
	at gov.uspto.patent.model.classification.IpcClassification.toString(IpcClassification.java:297)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at java.util.AbstractCollection.toString(AbstractCollection.java:462)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at gov.uspto.patent.model.Patent.toString(Patent.java:421)
	at gov.uspto.patent.doc.greenbook.Greenbook.parse(Greenbook.java:153)
	at gov.uspto.parser.dom4j.keyvalue.KvParser.parse(KvParser.java:49)
	at gov.uspto.patent.PatentReader.read(PatentReader.java:71)
	at gov.uspto.patent.TransformerCli.processDumpFile(TransformerCli.java:178)
	at gov.uspto.patent.TransformerCli.process(TransformerCli.java:122)
	at gov.uspto.patent.TransformerCli.main(TransformerCli.java:296)
```
Thanks!

**Comment by bgfeldm** [comment]
Fix has been checked in to ignore null parts/section of a Classification

**Comment by pedagogly** [comment]
Seems to be working; thanks.
