### ISSUE TITLE
TransformerCli throws an NPE when processing ipaipa090702.zip

### ISSUE THREAD

**Issue by pedagogly** [USPTO/PatentPublicData#28]
The following stacktrace results:

```
2017-01-11 14:20:39,877 INFO  [main] TransformerCli - Record: 'US20090165183A1' from ipa090702.zip:1
Exception in thread "main" java.lang.NullPointerException
	at gov.uspto.patent.model.classification.PatentClassification.compareTo(PatentClassification.java:144)
	at gov.uspto.patent.model.classification.PatentClassification.compareTo(PatentClassification.java:15)
	at java.util.TreeMap.compare(TreeMap.java:1294)
	at java.util.TreeMap.put(TreeMap.java:538)
	at java.util.TreeSet.add(TreeSet.java:255)
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1548)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at gov.uspto.patent.model.classification.PatentClassification.filter(PatentClassification.java:150)
	at gov.uspto.patent.model.classification.PatentClassification.filterByType(PatentClassification.java:155)
	at gov.uspto.patent.serialize.JsonMapper.mapClassifications(JsonMapper.java:138)
	at gov.uspto.patent.serialize.JsonMapper.buildJson(JsonMapper.java:113)
	at gov.uspto.patent.serialize.JsonMapper.write(JsonMapper.java:69)
	at gov.uspto.patent.serialize.JsonMapper.write(JsonMapper.java:57)
	at gov.uspto.patent.TransformerCli.write(TransformerCli.java:215)
	at gov.uspto.patent.TransformerCli.processDumpFile(TransformerCli.java:199)
	at gov.uspto.patent.TransformerCli.process(TransformerCli.java:122)
	at gov.uspto.patent.TransformerCli.main(TransformerCli.java:296)
```

Thanks.

**Comment by bgfeldm** [comment]
Checked in Fix.
