### ISSUE TITLE
Can't compile commit 7fdebf2189eb662308707ee0a3fd2eef15cc8568

### ISSUE THREAD

**Issue by patricknee** [USPTO/PatentPublicData#29]
New directory:

`git clone https://github.com/USPTO/PatentPublicData.git`

then 

`mvn clean package`

Results in:

```
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] PatentPublicData
[INFO] Common
[INFO] PatentDocument
[INFO] BulkDownloader
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building PatentPublicData 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ PatentPublicData ---
[INFO] 
[INFO] >>> maven-javadoc-plugin:2.10.3:aggregate (aggregate) > generate-sources @ PatentPublicData >>>
[INFO] 
[INFO] <<< maven-javadoc-plugin:2.10.3:aggregate (aggregate) < generate-sources @ PatentPublicData <<<
[INFO] 
[INFO] --- maven-javadoc-plugin:2.10.3:aggregate (aggregate) @ PatentPublicData ---
[INFO] Skipping javadoc generation
[INFO] 
[INFO] --- maven-javadoc-plugin:2.10.3:jar (attach-javadocs) @ PatentPublicData ---
[INFO] Skipping javadoc generation
[INFO] 
[INFO] --- maven-dependency-plugin:2.10:copy-dependencies (copy-dependencies) @ PatentPublicData ---
[INFO] 
[INFO] --- maven-assembly-plugin:2.2-beta-5:single (default) @ PatentPublicData ---
[INFO] Building zip: /Users/patrick/dev/repos/trashthis/PatentPublicData/target/PatentPublicData-0.0.1-SNAPSHOT.zip
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Common 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ Common ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ Common ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/patrick/dev/repos/trashthis/PatentPublicData/Common/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.5.1:compile (default-compile) @ Common ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 24 source files to /Users/patrick/dev/repos/trashthis/PatentPublicData/Common/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ Common ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.5.1:testCompile (default-testCompile) @ Common ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 3 source files to /Users/patrick/dev/repos/trashthis/PatentPublicData/Common/target/test-classes
[INFO] /Users/patrick/dev/repos/trashthis/PatentPublicData/Common/src/test/java/gov/uspto/common/text/StopWordTest.java: Some input files use or override a deprecated API.
[INFO] /Users/patrick/dev/repos/trashthis/PatentPublicData/Common/src/test/java/gov/uspto/common/text/StopWordTest.java: Recompile with -Xlint:deprecation for details.
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ Common ---
[INFO] Surefire report directory: /Users/patrick/dev/repos/trashthis/PatentPublicData/Common/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running gov.uspto.common.text.StopWordTest
Tests run: 31, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.203 sec
Running gov.uspto.common.text.StringCaseTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running gov.uspto.common.text.WordUtilTest
Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec

Results :

Tests run: 44, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- maven-jar-plugin:2.6:jar (default-jar) @ Common ---
[INFO] Building jar: /Users/patrick/dev/repos/trashthis/PatentPublicData/Common/target/Common-0.0.1-SNAPSHOT.jar
[INFO] 
[INFO] >>> maven-javadoc-plugin:2.10.3:aggregate (aggregate) > generate-sources @ Common >>>
[INFO] 
[INFO] <<< maven-javadoc-plugin:2.10.3:aggregate (aggregate) < generate-sources @ Common <<<
[INFO] 
[INFO] --- maven-javadoc-plugin:2.10.3:aggregate (aggregate) @ Common ---
[INFO] Skipping javadoc generation
[INFO] 
[INFO] --- maven-javadoc-plugin:2.10.3:jar (attach-javadocs) @ Common ---
[INFO] Skipping javadoc generation
[INFO] 
[INFO] --- maven-dependency-plugin:2.10:copy-dependencies (copy-dependencies) @ Common ---
[INFO] Copying commons-compress-1.11.jar to /Users/patrick/dev/repos/trashthis/PatentPublicData/Common/target/dependency-jars/commons-compress-1.11.jar
[INFO] Copying jopt-simple-5.0.2.jar to /Users/patrick/dev/repos/trashthis/PatentPublicData/Common/target/dependency-jars/jopt-simple-5.0.2.jar
[INFO] Copying commons-io-2.5.jar to /Users/patrick/dev/repos/trashthis/PatentPublicData/Common/target/dependency-jars/commons-io-2.5.jar
[INFO] Copying slf4j-api-1.7.21.jar to /Users/patrick/dev/repos/trashthis/PatentPublicData/Common/target/dependency-jars/slf4j-api-1.7.21.jar
[INFO] Copying slf4j-log4j12-1.7.21.jar to /Users/patrick/dev/repos/trashthis/PatentPublicData/Common/target/dependency-jars/slf4j-log4j12-1.7.21.jar
[INFO] Copying log4j-1.2.17.jar to /Users/patrick/dev/repos/trashthis/PatentPublicData/Common/target/dependency-jars/log4j-1.2.17.jar
[INFO] Copying guava-19.0.jar to /Users/patrick/dev/repos/trashthis/PatentPublicData/Common/target/dependency-jars/guava-19.0.jar
[INFO] 
[INFO] --- maven-assembly-plugin:2.2-beta-5:single (default) @ Common ---
[INFO] Building zip: /Users/patrick/dev/repos/trashthis/PatentPublicData/Common/target/Common-0.0.1-SNAPSHOT.zip
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building PatentDocument 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ PatentDocument ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ PatentDocument ---
[INFO] Using 'Cp1252' encoding to copy filtered resources.
[INFO] Copying 17 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.0:compile (default-compile) @ PatentDocument ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 209 source files to /Users/patrick/dev/repos/trashthis/PatentPublicData/PatentDocument/target/classes
[INFO] /Users/patrick/dev/repos/trashthis/PatentPublicData/PatentDocument/src/main/java/gov/uspto/patent/doc/sgml/items/DescriptionFigures.java: Some input files use unchecked or unsafe operations.
[INFO] /Users/patrick/dev/repos/trashthis/PatentPublicData/PatentDocument/src/main/java/gov/uspto/patent/doc/sgml/items/DescriptionFigures.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ PatentDocument ---
[INFO] Using 'Cp1252' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/patrick/dev/repos/trashthis/PatentPublicData/PatentDocument/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.0:testCompile (default-testCompile) @ PatentDocument ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 27 source files to /Users/patrick/dev/repos/trashthis/PatentPublicData/PatentDocument/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ PatentDocument ---
[INFO] Surefire report directory: /Users/patrick/dev/repos/trashthis/PatentPublicData/PatentDocument/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running gov.uspto.document.parser.dom4j.PatentParserTest
2017-01-12 09:55:18,015 WARN  [       main] UNDEFINED1234567     DescriptionNode - Patent does not have a Description.
2017-01-12 09:55:18,078 WARN  [       main] UNDEFINED1234567     DescriptionNode - Patent does not have a Description.
2017-01-12 09:55:18,100 WARN  [       main] US7654321            DescriptionNode - Patent does not have a Description.
2017-01-12 09:55:18,111 WARN  [       main] UNDEFINED1234567     DescriptionNode - Patent does not have a Description.
2017-01-12 09:55:18,137 WARN  [       main] US3930584            ApplicationIdNode - Invalid application-id 'APN' field not found
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.832 sec
Running gov.uspto.patent.doc.greenbook.FormattedTextTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.014 sec
Running gov.uspto.patent.doc.greenbook.GreenbookTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.255 sec
Running gov.uspto.patent.doc.greenbook.items.DescriptionFiguresTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.014 sec
Running gov.uspto.patent.doc.pap.PatentAppPubParserTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.674 sec
Running gov.uspto.patent.doc.sgml.SgmlTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.222 sec
Running gov.uspto.patent.doc.xml.ApplicationParserTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.424 sec
Running gov.uspto.patent.doc.xml.FormattedTextTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.017 sec
Running gov.uspto.patent.doc.xml.GrantParserTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.172 sec
Running gov.uspto.patent.mathml.MathMLTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec
Running gov.uspto.patent.model.classification.ClassificationPredicateTest
false
false
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.093 sec
Running gov.uspto.patent.model.classification.ClassificationTokenizerTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.006 sec
Running gov.uspto.patent.model.classification.CpCClassificationTest
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.007 sec
Running gov.uspto.patent.model.classification.IpcClassificationTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running gov.uspto.patent.model.classification.PatentClassificationTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.027 sec
Running gov.uspto.patent.model.classification.UspcClassificationTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.028 sec
Running gov.uspto.patent.model.DocumentIdTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.014 sec
Running gov.uspto.patent.model.entity.NamePersonTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec
Running gov.uspto.patent.model.PatentTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec
Running gov.uspto.patent.serialize.JsonMapperTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.03 sec
Running gov.uspto.patent.validate.AbstractRuleTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 sec
Running gov.uspto.patent.validate.ClaimRuleTest
Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.035 sec <<< FAILURE!
nullClaimListFail(gov.uspto.patent.validate.ClaimRuleTest)  Time elapsed: 0.034 sec  <<< ERROR!
java.lang.NullPointerException
	at gov.uspto.patent.model.Patent.setClaim(Patent.java:157)
	at gov.uspto.patent.validate.ClaimRuleTest.nullClaimListFail(ClaimRuleTest.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Running gov.uspto.patent.validate.ClassificationRuleTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec
Running gov.uspto.patent.validate.DescriptionRuleTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec
Running gov.uspto.patent.validate.TitleRuleTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec

Results :

Tests in error: 
  nullClaimListFail(gov.uspto.patent.validate.ClaimRuleTest)

Tests run: 71, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] PatentPublicData ................................... SUCCESS [  5.361 s]
[INFO] Common ............................................. SUCCESS [  5.228 s]
[INFO] PatentDocument ..................................... FAILURE [ 11.048 s]
[INFO] BulkDownloader ..................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 21.818 s
[INFO] Finished at: 2017-01-12T09:55:24+01:00
[INFO] Final Memory: 30M/280M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project PatentDocument: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/patrick/dev/repos/trashthis/PatentPublicData/PatentDocument/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :PatentDocument
```

**Comment by bgfeldm** [comment]
I have removed the unit test.

**Comment by patricknee** [comment]
Yes, compiles now. Thanks.
