### ISSUE TITLE
Multiple versions of JSoup causing exception

### ISSUE THREAD

**Issue by pedagogly** [USPTO/PatentPublicData#30]
The BulkDownloader POM calls for the prior version of Jsoup, which leads to both versions being placed in the dependency jar directory, and the following exception:
```
Exception in thread "main" java.lang.NoSuchMethodError: org.jsoup.parser.Parser.settings(Lorg/jsoup/parser/ParseSettings;)Lorg/jsoup/parser/Parser;	
	at gov.uspto.patent.PatentReader.fixTagsJDOM(PatentReader.java:116)
	at gov.uspto.patent.PatentReader.getJDOM(PatentReader.java:99)
	at gov.uspto.patent.PatentReader.read(PatentReader.java:76)
	at gov.uspto.patent.TransformerCli.processDumpFile(TransformerCli.java:178)
	at gov.uspto.patent.TransformerCli.process(TransformerCli.java:122)
	at gov.uspto.patent.TransformerCli.main(TransformerCli.java:296)
```

**Comment by bgfeldm** [comment]
Fixed
