### ISSUE TITLE
TransformerCli throws NumberFormatException and stops processing with  ipg060110.zip

### ISSUE THREAD

**Issue by pedagogly** [USPTO/PatentPublicData#33]
```
2017-01-12 13:18:22,562 INFO  [main] TransformerCli - Record: 'US6985272B2' from ipg060110.zip:1903
Exception in thread "main" java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:592)
	at java.lang.Integer.valueOf(Integer.java:766)
	at gov.uspto.patent.model.classification.IpcClassification.standardize(IpcClassification.java:123)
	at gov.uspto.patent.model.classification.IpcClassification.toString(IpcClassification.java:288)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at java.util.AbstractCollection.toString(AbstractCollection.java:462)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at gov.uspto.patent.model.Patent.toString(Patent.java:429)
	at gov.uspto.patent.doc.xml.GrantParser.parse(GrantParser.java:168)
	at gov.uspto.patent.PatentReader.read(PatentReader.java:74)
	at gov.uspto.patent.TransformerCli.processDumpFile(TransformerCli.java:178)
	at gov.uspto.patent.TransformerCli.process(TransformerCli.java:122)
	at gov.uspto.patent.TransformerCli.main(TransformerCli.java:296)

```

**Comment by bgfeldm** [comment]
Fixed.. checking if main group string is numeric before converting to integer.
