### ISSUE TITLE
TransformerCli throws an NPE and stops processing with pftaps19931130_wk48.zip

### ISSUE THREAD

**Issue by pedagogly** [USPTO/PatentPublicData#34]
```
2017-01-12 13:37:00,537 INFO  [main] TransformerCli - Record: 'US5266142A' from pftaps19931130_wk48.zip:1102			
Exception in thread "main" java.lang.NullPointerException				
	at gov.uspto.patent.serialize.JsonMapper.mapName(JsonMapper.java:376)	
	at gov.uspto.patent.serialize.JsonMapper.mapAssignees(JsonMapper.java:320)
	at gov.uspto.patent.serialize.JsonMapper.buildJson(JsonMapper.java:102)		
	at gov.uspto.patent.serialize.JsonMapper.write(JsonMapper.java:69)
	at gov.uspto.patent.serialize.JsonMapper.write(JsonMapper.java:57)	
	at gov.uspto.patent.TransformerCli.write(TransformerCli.java:215)
	at gov.uspto.patent.TransformerCli.processDumpFile(TransformerCli.java:199)
	at gov.uspto.patent.TransformerCli.process(TransformerCli.java:122)						
	at gov.uspto.patent.TransformerCli.main(TransformerCli.java:296)
```

**Comment by bgfeldm** [comment]
Checked in Fix to skip Assignee if name is null.
