### ISSUE TITLE
TransformerCli throws a NPE and stops processing with pftaps19860826_wk34.zip

### ISSUE THREAD

**Issue by pedagogly** [USPTO/PatentPublicData#41]
```
2017-01-20 11:03:44,700 INFO  [main] TransformerCli - Record: 'US4607439A' from pftaps19860826_wk34.zip:176
Exception in thread "main" java.lang.NullPointerException
	at gov.uspto.patent.serialize.JsonMapper.mapName(JsonMapper.java:376)
	at gov.uspto.patent.serialize.JsonMapper.mapInventors(JsonMapper.java:336)
	at gov.uspto.patent.serialize.JsonMapper.buildJson(JsonMapper.java:101)
	at gov.uspto.patent.serialize.JsonMapper.write(JsonMapper.java:69)
	at gov.uspto.patent.serialize.JsonMapper.write(JsonMapper.java:57)
	at gov.uspto.patent.TransformerCli.write(TransformerCli.java:217)
	at gov.uspto.patent.TransformerCli.processDumpFile(TransformerCli.java:201)
	at gov.uspto.patent.TransformerCli.process(TransformerCli.java:122)
	at gov.uspto.patent.TransformerCli.main(TransformerCli.java:298)

```

**Comment by bgfeldm** [comment]
```
INVT
NAM  1
```

Fails because Inventor name is invalid: "1" ; which gets carried along as Null.

I will change the code to keep the value and but still throw a warning.
