### ISSUE TITLE
Old vs. New Downloader

### ISSUE THREAD

**Issue by patricknee** [USPTO/PatentPublicData#5]
I am getting a 404 error when requesting 2000 or earlier using gov.uspto.bulkdata.cli2.BulkData.  (see bottom)

I see the data formats change at this time, with 2001 in SGML and 2002+ in XML. Is one to use gov.uspto.bulkdata.cli.Download for years before 2001? 

It appears Download does not take years as a parameter. Does it just download all years? It appears to have started downloading 2015 (file names ipa150101.zip, etc.)...

Thanks.

gov.uspto.bulkdata.cli2.BulkData --type=application --years=2000 --outdir="${PROJECTPATH}/download/patents2000"

Exception in thread "main" java.io.IOException: Unexpected server response code 404
	at gov.uspto.bulkdata.PageLinkScraper.fetchLinks(PageLinkScraper.java:88)
	at gov.uspto.bulkdata.PageLinkScraper.fetchLinks(PageLinkScraper.java:41)
	at gov.uspto.bulkdata.cli2.BulkData.fetchLinks(BulkData.java:145)
	at gov.uspto.bulkdata.cli2.BulkData.fetchLinks(BulkData.java:152)
	at gov.uspto.bulkdata.cli2.BulkData.download(BulkData.java:73)
	at gov.uspto.bulkdata.cli2.BulkData.main(BulkData.java:243)

**Comment by bgfeldm** [comment]
Your trying to download Patent Applications which where made public after 2002.

To download Granted Patents, use the type "grant"

**Comment by patricknee** [comment]
Thanks! I may have taken me a while to chase that down.
