### ISSUE TITLE
TransformerCli throws an NPE and stops processing pftaps19920714_wk28.zip

### ISSUE THREAD

**Issue by pedagogly** [USPTO/PatentPublicData#50]
```
2017-01-26 15:06:08,005 INFO  [main] TransformerCli - Record: 'US5129494A' from pftaps19920714_wk28.zip:612	
Exception in thread "main" java.lang.NullPointerException	
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)
	at com.google.common.base.Splitter.splitToList(Splitter.java:408)
	at gov.uspto.patent.doc.greenbook.items.NameNode.read(NameNode.java:29)
	at gov.uspto.patent.doc.greenbook.fragments.InventorNode.readInventor(InventorNode.java:41)
	at gov.uspto.patent.doc.greenbook.fragments.InventorNode.read(InventorNode.java:31)
	at gov.uspto.patent.doc.greenbook.Greenbook.parse(Greenbook.java:132)
	at gov.uspto.parser.dom4j.keyvalue.KvParser.parse(KvParser.java:65)
	at gov.uspto.patent.PatentReader.read(PatentReader.java:70)
	at gov.uspto.patent.TransformerCli.processDumpFile(TransformerCli.java:180)
	at gov.uspto.patent.TransformerCli.process(TransformerCli.java:122)
	at gov.uspto.patent.TransformerCli.main(TransformerCli.java:298)
```
A similar StackTrace occurs with:
pftaps19880426_wk17.zip
pftaps19881004_wk40.zip
pftaps19890214_wk07.zip
pftaps19890627_wk26.zip
pftaps19890801_wk31.zip
pftaps19890815_wk33.zip
pftaps19890829_wk35.zip
pftaps19900130_wk05.zip
pftaps19900925_wk39.zip
pftaps19910212_wk07.zip
pftaps19910409_wk15.zip
pftaps19911008_wk41.zip
pftaps19920324_wk12.zip
pftaps19921020_wk42.zip
pftaps19930518_wk20.zip
pftaps19931130_wk48.zip
pftaps19940322_wk12.zip
pftaps19940524_wk21.zip
pftaps19940705_wk27.zip
pftaps19940809_wk32.zip
pftaps19941227_wk52.zip
pftaps19950328_wk13.zip
pftaps19950404_wk14.zip
pftaps19950815_wk33.zip
pftaps19951017_wk42.zip
pftaps19951212_wk50.zip

**Comment by bgfeldm** [comment]
Looks like an error I fixed previously.  I don't get an NPE when running TransformerCli  on pftaps19880426_wk17.zip.  Try rebuilding and deploying the updated jar file.  And let me know if you are still getting an issue.

**Comment by pedagogly** [comment]
Thanks, you are correct.  I should have checked for changes and incorporated them before posting a bug.  All the GreenBook files work now.
