### ISSUE TITLE
Fatal errors processing full files 

### ISSUE THREAD

**Issue by patricknee** [USPTO/PatentPublicData#8]
Processing samples of full filse from 1980, 1990, 2000 and 2010 resulted in fatal errors after 100s of files (earlier testing was with limit=10). Three different errors occurred (based on dumps). Specific files (downloaded for cited year with limit=2) are listed below. One example of each error type is included in the post.

Specific files:
1980: pftaps19800101_wk01.zip     Error type 1
1990: pftaps19900102_wk01.zip    Error type 1
2000: pftaps20000104_wk01.zip    Error type 2
2010: ipg100105.zip     Error type 3

```
patrick$ java -cp PatentDocument/target/*:PatentDocument/target/dependency-jars/*:resources gov.uspto.patent.TransformerCli --input="BulkDownloader/download/grants/1990/pftaps19900102_wk01.zip" --outBulk=false --outdir="BulkDownloader/download/grants/1990/expanded/"
2016-11-08 21:49:27,321 INFO  [main] TransformerCli - --- Start ---
2016-11-08 21:49:27,356 INFO  [main] TransformerCli - Dump File[1]: /Users/patrick/dev/repos/PatentPublicData/BulkDownloader/download/grants/1990/pftaps19900102_wk01.zip
2016-11-08 21:49:27,358 INFO  [main] PatentDocFormatDetect - PatentDocFormat fromFileName: Greenbook
2016-11-08 21:49:27,361 INFO  [main] ZipReader - Reading zip file: /Users/patrick/dev/repos/PatentPublicData/BulkDownloader/download/grants/1990/pftaps19900102_wk01.zip
2016-11-08 21:49:27,410 INFO  [main] ZipReader - Found 1 file[FileFilter [matchRules=[]]]: pftaps19900102_wk01.txt
2016-11-08 21:49:27,412 INFO  [main] PatentDocFormatDetect - PatentType fromContent: Greenbook
2016-11-08 21:49:27,610 WARN  [main] AbstractTextNode - Patent does not have an Abstract
2016-11-08 21:49:27,715 INFO  [main] TransformerCli - Record: 'US305275' from /Users/patrick/dev/repos/PatentPublicData/BulkDownloader/download/grants/1990/pftaps19900102_wk01.zip:1
2016-11-08 21:49:27,776 WARN  [main] AbstractTextNode - Patent does not have an Abstract
2016-11-08 21:49:27,780 INFO  [main] TransformerCli - Record: 'US305277' from /Users/patrick/dev/repos/PatentPublicData/BulkDownloader/download/grants/1990/pftaps19900102_wk01.zip:2
2016-11-08 21:49:27,812 WARN  [main] AbstractTextNode - Patent does not have an Abstract
2016-11-08 21:49:27,815 INFO  [main] TransformerCli - Record: 'US305279' from /Users/patrick/dev/repos/PatentPublicData/BulkDownloader/download/grants/1990/pftaps19900102_wk01.zip:3
2016-11-08 21:49:27,838 WARN  [main] AbstractTextNode - Patent does not have an Abstract
2016-11-08 21:49:27,841 INFO  [main] TransformerCli - Record: 'US305281' from /Users/patrick/dev/repos/PatentPublicData/BulkDownloader/download/grants/1990/pftaps19900102_wk01.zip:4
2016-11-08 21:49:27,858 WARN  [main] AbstractTextNode - Patent does not have an Abstract
(trimmed)
2016-11-08 21:49:41,038 INFO  [main] TransformerCli - Record: 'US4891829' from /Users/patrick/dev/repos/PatentPublicData/BulkDownloader/download/grants/1990/pftaps19900102_wk01.zip:806
2016-11-08 21:49:41,064 INFO  [main] TransformerCli - Record: 'US4891831' from /Users/patrick/dev/repos/PatentPublicData/BulkDownloader/download/grants/1990/pftaps19900102_wk01.zip:807
2016-11-08 21:49:41,075 WARN  [main] ClassificationNode - Failed to Parse IPC Classification: 'G21K  104' from : <CLAS><OCL>378145</OCL><XCL>378146</XCL><XCL>378151</XCL><XCL>378152</XCL><EDF>4</EDF><ICL>G21K  104</ICL><FSC>378</FSC><FSS>8;19;145-147;95;150;151;152;205</FSS></CLAS>
2016-11-08 21:49:41,077 INFO  [main] TransformerCli - Record: 'US4891833' from /Users/patrick/dev/repos/PatentPublicData/BulkDownloader/download/grants/1990/pftaps19900102_wk01.zip:808
2016-11-08 21:49:41,086 WARN  [main] ClassificationNode - Failed to Parse IPC Classification: 'H04M  164' from : <CLAS><OCL>379 88</OCL><XCL>379 45</XCL><XCL>379 51</XCL><XCL>379 73</XCL><EDF>4</EDF><ICL>H04M  164</ICL><FSC>379</FSC><FSS>41;45;48;51;67;84;88;89;110;73</FSS><FSC>369</FSC><FSS>2;14;24;83</FSS><FSC>360</FSC><FSS>32</FSS></CLAS>
2016-11-08 21:49:41,088 INFO  [main] TransformerCli - Record: 'US4891835' from /Users/patrick/dev/repos/PatentPublicData/BulkDownloader/download/grants/1990/pftaps19900102_wk01.zip:809
2016-11-08 21:49:41,113 WARN  [main] ClassificationNode - Failed to Parse IPC Classification: 'H04M  160' from : <CLAS><OCL>379390</OCL><XCL>379388</XCL><XCL>381106</XCL><EDF>4</EDF><ICL>H04M  160</ICL><FSC>381</FSC><FSS>68;684;94;96;102;106;107;111;72;113</FSS><FSC>379</FSC><FSS>388;389;390;395;387</FSS></CLAS>
2016-11-08 21:49:41,114 INFO  [main] TransformerCli - Record: 'US4891837' from /Users/patrick/dev/repos/PatentPublicData/BulkDownloader/download/grants/1990/pftaps19900102_wk01.zip:810
2016-11-08 21:49:41,133 WARN  [main] ClassificationNode - Failed to Parse IPC Classification: 'H04S  300' from : <CLAS><OCL>381 22</OCL><EDF>4</EDF><ICL>H04S  300</ICL><FSC>381</FSC><FSS>17;18;19;20;21;22;23</FSS></CLAS>
2016-11-08 21:49:41,135 INFO  [main] TransformerCli - Record: 'US4891839' from /Users/patrick/dev/repos/PatentPublicData/BulkDownloader/download/grants/1990/pftaps19900102_wk01.zip:811
2016-11-08 21:49:41,180 WARN  [main] ClassificationNode - Failed to Parse IPC Classification: 'H03G  500' from : <CLAS><OCL>351 98</OCL><XCL>333 28T</XCL><EDF>4</EDF><ICL>H03G  500</ICL><FSC>328</FSC><FSS>28 T;28 R</FSS><FSC>381</FSC><FSS>98;103</FSS></CLAS>
2016-11-08 21:49:41,181 INFO  [main] TransformerCli - Record: 'US4891841' from /Users/patrick/dev/repos/PatentPublicData/BulkDownloader/download/grants/1990/pftaps19900102_wk01.zip:812
2016-11-08 21:49:41,190 INFO  [main] TransformerCli - Record: 'US4891843' from /Users/patrick/dev/repos/PatentPublicData/BulkDownloader/download/grants/1990/pftaps19900102_wk01.zip:813
Exception in thread "main" java.util.NoSuchElementException
	at gov.uspto.patent.bulk.DumpFileAps.read(DumpFileAps.java:50)
	at gov.uspto.patent.bulk.DumpFile.next(DumpFile.java:92)
	at gov.uspto.patent.bulk.DumpFile.next(DumpFile.java:23)
	at gov.uspto.patent.TransformerCli.processDumpFile(TransformerCli.java:160)
	at gov.uspto.patent.TransformerCli.process(TransformerCli.java:116)
	at gov.uspto.patent.TransformerCli.main(TransformerCli.java:276)
```

```
patrick$ java -cp PatentDocument/target/*:PatentDocument/target/dependency-jars/*:resources gov.uspto.patent.TransformerCli --input="BulkDownloader/download/grants/2000/pftaps20000104_wk01.zip" --outBulk=false --outdir="BulkDownloader/download/grants/2000/expanded/"
2016-11-08 21:50:34,345 INFO  [main] TransformerCli - --- Start ---
2016-11-08 21:50:34,379 INFO  [main] TransformerCli - Dump File[1]: /Users/patrick/dev/repos/PatentPublicData/BulkDownloader/download/grants/2000/pftaps20000104_wk01.zip
2016-11-08 21:50:34,382 INFO  [main] PatentDocFormatDetect - PatentDocFormat fromFileName: Greenbook
2016-11-08 21:50:34,386 INFO  [main] ZipReader - Reading zip file: /Users/patrick/dev/repos/PatentPublicData/BulkDownloader/download/grants/2000/pftaps20000104_wk01.zip
2016-11-08 21:50:34,418 INFO  [main] ZipReader - Found 1 file[FileFilter [matchRules=[]]]: pftaps20000104_wk01.txt
2016-11-08 21:50:34,420 INFO  [main] PatentDocFormatDetect - PatentType fromContent: Greenbook
2016-11-08 21:50:34,599 WARN  [main] ClassificationNode - Failed to Parse IPC Classification: '0205' from : <CLAS><OCL>D 2602</OCL><XCL>D2608</XCL><XCL>D2627</XCL><EDF>6</EDF><ICL>0205</ICL><FSC>D 2</FSC><FSS>600;602;608;609;624;627;639;859;891</FSS><FSC>2</FSC><FSS>236;237;232;269;338;124;125;115</FSS></CLAS>
2016-11-08 21:50:34,608 WARN  [main] AbstractTextNode - Patent does not have an Abstract
2016-11-08 21:50:34,709 INFO  [main] TransformerCli - Record: 'US418273' from /Users/patrick/dev/repos/PatentPublicData/BulkDownloader/download/grants/2000/pftaps20000104_wk01.zip:1
2016-11-08 21:50:34,779 WARN  [main] ClassificationNode - Failed to Parse IPC Classification: '0207' from : <CLAS><OCL>D 2639</OCL><EDF>6</EDF><ICL>0207</ICL><FSC>D11</FSC><FSS>200-201;261;55-66</FSS><FSC>D 2</FSC><FSS>639</FSS><FSC>297</FSC><FSS>482</FSS><FSC>24</FSC><FSS>633</FSS><FSC>D21</FSC><FSS>604</FSS><FSC>428</FSC><FSS>100</FSS></CLAS>
2016-11-08 21:50:34,782 WARN  [main] AbstractTextNode - Patent does not have an Abstract
2016-11-08 21:50:34,784 INFO  [main] TransformerCli - Record: 'US418275' from /Users/patrick/dev/repos/PatentPublicData/BulkDownloader/download/grants/2000/pftaps20000104_wk01.zip:2
2016-11-08 21:50:34,810 WARN  [main] ClassificationNode - Failed to Parse IPC Classification: '0202' from : <CLAS><OCL>D 2743</OCL><EDF>6</EDF><ICL>0202</ICL><FSC>D 2</FSC><FSS>728;743;746;753;830;838</FSS><FSC>D 5</FSC><FSS>62</FSS><FSC>2</FSC><FSS>69;94;1;40;227</FSS></CLAS>
2016-11-08 21:50:34,813 WARN  [main] AbstractTextNode - Patent does not have an Abstract
2016-11-08 21:50:34,818 INFO  [main] TransformerCli - Record: 'US418277' from /Users/patrick/dev/repos/PatentPublicData/BulkDownloader/download/grants/2000/pftaps20000104_wk01.zip:3
2016-11-08 21:50:34,841 WARN  [main] ClassificationNode - Failed to Parse IPC Classification: '0203' from : <CLAS><OCL>D 2882</OCL><EDF>6</EDF><ICL>0203</ICL><FSC>D 2</FSC><FSS>865;866;872;876;879;882;883;884;886;887</FSS><FSC>D29</FSC><FSS>102;104</FSS><FSC>2</FSC><FSS>171;181;195.1;412;419;209.13</FSS></CLAS>
2016-11-08 21:50:34,850 WARN  [main] AbstractTextNode - Patent does not have an Abstract
(Trimmed)
2016-11-08 21:50:58,508 WARN  [main] ClassificationNode - Failed to Parse IPC Classification: 'G02F  11335' from : <CLAS><OCL>349113</OCL><XCL>349139</XCL><EDF>6</EDF><ICL>G02F  11335</ICL><ICL>G02F  11343</ICL><FSC>349</FSC><FSS>113;149;151;152;139</FSS></CLAS>
2016-11-08 21:50:58,509 INFO  [main] TransformerCli - Record: 'US6011605' from /Users/patrick/dev/repos/PatentPublicData/BulkDownloader/download/grants/2000/pftaps20000104_wk01.zip:1224
2016-11-08 21:50:58,521 WARN  [main] ClassificationNode - Failed to Parse IPC Classification: 'G02F  11339' from : <CLAS><OCL>349153</OCL><XCL>349151</XCL><EDF>6</EDF><ICL>G02F  11339</ICL><FSC>349</FSC><FSS>149;151;153</FSS></CLAS>
2016-11-08 21:50:58,522 INFO  [main] TransformerCli - Record: 'US6011607' from /Users/patrick/dev/repos/PatentPublicData/BulkDownloader/download/grants/2000/pftaps20000104_wk01.zip:1225
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 1
	at java.lang.String.substring(String.java:1963)
	at gov.uspto.patent.model.entity.NamePerson.getAbbreviatedName(NamePerson.java:75)
	at gov.uspto.patent.serialize.JsonMapper.mapName(JsonMapper.java:370)
	at gov.uspto.patent.serialize.JsonMapper.mapAssignees(JsonMapper.java:319)
	at gov.uspto.patent.serialize.JsonMapper.buildJson(JsonMapper.java:101)
	at gov.uspto.patent.serialize.JsonMapper.write(JsonMapper.java:68)
	at gov.uspto.patent.serialize.JsonMapper.write(JsonMapper.java:56)
	at gov.uspto.patent.TransformerCli.write(TransformerCli.java:203)
	at gov.uspto.patent.TransformerCli.processDumpFile(TransformerCli.java:188)
	at gov.uspto.patent.TransformerCli.process(TransformerCli.java:116)
	at gov.uspto.patent.TransformerCli.main(TransformerCli.java:276)
```

```
patrick$ java -cp PatentDocument/target/*:PatentDocument/target/dependency-jars/*:resources gov.uspto.patent.TransformerCli --input="BulkDownloader/download/grants/2010/ipg100105.zip" --outBulk=false --outdir="BulkDownloader/download/grants/2010/expanded/"
2016-11-08 21:51:36,523 INFO  [main] TransformerCli - --- Start ---
2016-11-08 21:51:36,560 INFO  [main] TransformerCli - Dump File[1]: /Users/patrick/dev/repos/PatentPublicData/BulkDownloader/download/grants/2010/ipg100105.zip
2016-11-08 21:51:36,562 INFO  [main] PatentDocFormatDetect - PatentDocFormat fromFileName: RedbookGrant
2016-11-08 21:51:36,569 INFO  [main] ZipReader - Reading zip file: /Users/patrick/dev/repos/PatentPublicData/BulkDownloader/download/grants/2010/ipg100105.zip
2016-11-08 21:51:36,601 INFO  [main] ZipReader - Found 1 file[FileFilter [matchRules=[SuffixFilter [suffixes=[xml]]]]]: ipg100105.xml
2016-11-08 21:51:36,604 INFO  [main] PatentDocFormatDetect - PatentType fromContent: RedbookGrant
2016-11-08 21:51:37,205 INFO  [main] TransformerCli - Record: 'USD0607176S1' from /Users/patrick/dev/repos/PatentPublicData/BulkDownloader/download/grants/2010/ipg100105.zip:1
2016-11-08 21:51:37,351 INFO  [main] TransformerCli - Record: 'USD0607177S1' from /Users/patrick/dev/repos/PatentPublicData/BulkDownloader/download/grants/2010/ipg100105.zip:2
2016-11-08 21:51:37,463 INFO  [main] TransformerCli - Record: 'USD0607178S1' from /Users/patrick/dev/repos/PatentPublicData/BulkDownloader/download/grants/2010/ipg100105.zip:3
2016-11-08 21:51:37,601 INFO  [main] TransformerCli - Record: 'USD0607179S1' from /Users/patrick/dev/repos/PatentPublicData/BulkDownloader/download/grants/2010/ipg100105.zip:4
2016-11-08 21:51:37,738 INFO  [main] TransformerCli - Record: 'USD0607180S1' from /Users/patrick/dev/repos/PatentPublicData/BulkDownloader/download/grants/2010/ipg100105.zip:5

.......(trimmed)
2016-11-08 21:55:32,444 INFO  [main] TransformerCli - Record: 'US7642067B2' from /Users/patrick/dev/repos/PatentPublicData/BulkDownloader/download/grants/2010/ipg100105.zip:1937
2016-11-08 21:55:32,555 INFO  [main] TransformerCli - Record: 'US7642068B2' from /Users/patrick/dev/repos/PatentPublicData/BulkDownloader/download/grants/2010/ipg100105.zip:1938
2016-11-08 21:55:32,618 INFO  [main] TransformerCli - Record: 'US7642069B2' from /Users/patrick/dev/repos/PatentPublicData/BulkDownloader/download/grants/2010/ipg100105.zip:1939
Exception in thread "main" java.lang.NullPointerException
	at gov.uspto.patent.model.entity.NamePerson.getAbbreviatedName(NamePerson.java:75)
	at gov.uspto.patent.serialize.JsonMapper.mapName(JsonMapper.java:370)
	at gov.uspto.patent.serialize.JsonMapper.mapApplicant(JsonMapper.java:306)
	at gov.uspto.patent.serialize.JsonMapper.buildJson(JsonMapper.java:99)
	at gov.uspto.patent.serialize.JsonMapper.write(JsonMapper.java:68)
	at gov.uspto.patent.serialize.JsonMapper.write(JsonMapper.java:56)
	at gov.uspto.patent.TransformerCli.write(TransformerCli.java:203)
	at gov.uspto.patent.TransformerCli.processDumpFile(TransformerCli.java:188)
	at gov.uspto.patent.TransformerCli.process(TransformerCli.java:116)
	at gov.uspto.patent.TransformerCli.main(TransformerCli.java:276)
```

**Comment by patricknee** [comment]
Splitting into multiple issues.
