### ISSUE TITLE
TransformerCli fails for US7632515B2 in ipg091215.zip

### ISSUE THREAD

**Issue by legolego** [USPTO/PatentPublicData#81]
Running TransformerCli on ipg091215.zip fails on patent US7632515B2 (attached xml file) and kicks me out to the command prompt.

`2019-02-26 11:16:18,653 INFO  [main] TransformerCli - Record: 'US7632513B2' from D:\patents\ipg091215.zip:1647`
`2019-02-26 11:16:18,752 INFO  [main] TransformerCli - Record: 'US7632514B2' from D:\patents\ipg091215.zip:1648`
`2019-02-26 11:16:19,883 INFO  [main] TransformerCli - Record: 'US7632515B2' from D:\patents\ipg091215.zip:1649`
`Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 0
        at java.base/java.lang.StringLatin1.charAt(Unknown Source)
       at java.base/java.lang.String.charAt(Unknown Source)
       at gov.uspto.common.text.StringCaseUtil.toTitleCase(StringCaseUtil.java:100)
       at gov.uspto.patent.doc.xml.GrantParser.parse(GrantParser.java:69)
        at gov.uspto.parser.dom4j.Dom4JParser.parse(Dom4JParser.java:90)
        at gov.uspto.patent.PatentReader.read(PatentReader.java:82)
        at gov.uspto.patent.TransformerCli.processDumpFile(TransformerCli.java:187)
        at gov.uspto.patent.TransformerCli.process(TransformerCli.java:129)
        at gov.uspto.patent.TransformerCli.main(TransformerCli.java:307)`

[07632515.zip](https://github.com/USPTO/PatentPublicData/files/2906495/07632515.zip)

**Comment by legolego** [comment]
Thank you! :)
