### ISSUE TITLE
End of file error?

### ISSUE THREAD

**Issue by patricknee** [USPTO/PatentPublicData#9]
I am splitting the error types reported yesterday into separate issues. 

I now have the code up and running in a debugger, but I am not yet familiar enough with the program flow and data to be confident of correct behaviors. However, I will help try to debug.

Regarding the error shown below, I am testing with this file: 1980  pftaps19800101_wk01.zip

It is crashing on an explicitly thrown exception on gov.uspto.patent.bulk.DumpFileAps.read(DumpFileAps.java:50). 

As far as I can tell so far: This is thrown at the end of a line-by-line read of the input file designed to break the file into individual blobs of text representing a single patent. Looking at the data, each patent is separated by a line PATN. This is the start tag. The code runs until it finds the next PATN, and sends back the preceeding accumulated text as the patent. Then it starts accumulating text to represent the next patent. 

Since there is not EOF file marker, when super.getReader().readLine()) == null the WHILE exits, the last accumulated patent data is not returned, and the exception of line 50 is thrown. That is: it appears that (at least for files of this type; I haven't looked at other files yet) this code will ALWAYS crash on the last patent, and will always NOT return the last patent's test.

Commenting out line 50 and inserting the return of the accumulated text allows the file to return the last patent. This function is called one last time, so the content.length() has to be checked and if it is zero, return NULL to stop program flow. (Again, I don't know the data enough to know whether this is correct.)

With this following change, this 1980s file completes. 

```
		//throw new NoSuchElementException();
		if (content.length()==0){
			return null;
		}
		else { 
			return startTag + "\n" + content.toString();
		}
```

Error messages with current code below:

```
patrick$ java -cp PatentDocument/target/*:PatentDocument/target/dependency-jars/*:resources gov.uspto.patent.TransformerCli --input="BulkDownloader/download/grants/1990/pftaps19900102_wk01.zip" --outBulk=false --outdir="BulkDownloader/download/grants/1990/expanded/"
2016-11-08 21:49:27,321 INFO  [main] TransformerCli - --- Start ---
2016-11-08 21:49:27,356 INFO  [main] TransformerCli - Dump File[1]: /Users/patrick/dev/repos/PatentPublicData/BulkDownloader/download/grants/1990/pftaps19900102_wk01.zip
2016-11-08 21:49:27,358 INFO  [main] PatentDocFormatDetect - PatentDocFormat fromFileName: Greenbook
2016-11-08 21:49:27,361 INFO  [main] ZipReader - Reading zip file: /Users/patrick/dev/repos/PatentPublicData/BulkDownloader/download/grants/1990/pftaps19900102_wk01.zip
2016-11-08 21:49:27,410 INFO  [main] ZipReader - Found 1 file[FileFilter [matchRules=[]]]: pftaps19900102_wk01.txt
2016-11-08 21:49:27,412 INFO  [main] PatentDocFormatDetect - PatentType fromContent: Greenbook
2016-11-08 21:49:27,610 WARN  [main] AbstractTextNode - Patent does not have an Abstract
2016-11-08 21:49:27,715 INFO  [main] TransformerCli - Record: 'US305275' from /Users/patrick/dev/repos/PatentPublicData/BulkDownloader/download/grants/1990/pftaps19900102_wk01.zip:1
2016-11-08 21:49:27,776 WARN  [main] AbstractTextNode - Patent does not have an Abstract
2016-11-08 21:49:27,780 INFO  [main] TransformerCli - Record: 'US305277' from /Users/patrick/dev/repos/PatentPublicData/BulkDownloader/download/grants/1990/pftaps19900102_wk01.zip:2
2016-11-08 21:49:27,812 WARN  [main] AbstractTextNode - Patent does not have an Abstract
2016-11-08 21:49:27,815 INFO  [main] TransformerCli - Record: 'US305279' from /Users/patrick/dev/repos/PatentPublicData/BulkDownloader/download/grants/1990/pftaps19900102_wk01.zip:3
2016-11-08 21:49:27,838 WARN  [main] AbstractTextNode - Patent does not have an Abstract
2016-11-08 21:49:27,841 INFO  [main] TransformerCli - Record: 'US305281' from /Users/patrick/dev/repos/PatentPublicData/BulkDownloader/download/grants/1990/pftaps19900102_wk01.zip:4
2016-11-08 21:49:27,858 WARN  [main] AbstractTextNode - Patent does not have an Abstract
(trimmed)
2016-11-08 21:49:41,038 INFO  [main] TransformerCli - Record: 'US4891829' from /Users/patrick/dev/repos/PatentPublicData/BulkDownloader/download/grants/1990/pftaps19900102_wk01.zip:806
2016-11-08 21:49:41,064 INFO  [main] TransformerCli - Record: 'US4891831' from /Users/patrick/dev/repos/PatentPublicData/BulkDownloader/download/grants/1990/pftaps19900102_wk01.zip:807
2016-11-08 21:49:41,075 WARN  [main] ClassificationNode - Failed to Parse IPC Classification: 'G21K  104' from : <CLAS><OCL>378145</OCL><XCL>378146</XCL><XCL>378151</XCL><XCL>378152</XCL><EDF>4</EDF><ICL>G21K  104</ICL><FSC>378</FSC><FSS>8;19;145-147;95;150;151;152;205</FSS></CLAS>
2016-11-08 21:49:41,077 INFO  [main] TransformerCli - Record: 'US4891833' from /Users/patrick/dev/repos/PatentPublicData/BulkDownloader/download/grants/1990/pftaps19900102_wk01.zip:808
2016-11-08 21:49:41,086 WARN  [main] ClassificationNode - Failed to Parse IPC Classification: 'H04M  164' from : <CLAS><OCL>379 88</OCL><XCL>379 45</XCL><XCL>379 51</XCL><XCL>379 73</XCL><EDF>4</EDF><ICL>H04M  164</ICL><FSC>379</FSC><FSS>41;45;48;51;67;84;88;89;110;73</FSS><FSC>369</FSC><FSS>2;14;24;83</FSS><FSC>360</FSC><FSS>32</FSS></CLAS>
2016-11-08 21:49:41,088 INFO  [main] TransformerCli - Record: 'US4891835' from /Users/patrick/dev/repos/PatentPublicData/BulkDownloader/download/grants/1990/pftaps19900102_wk01.zip:809
2016-11-08 21:49:41,113 WARN  [main] ClassificationNode - Failed to Parse IPC Classification: 'H04M  160' from : <CLAS><OCL>379390</OCL><XCL>379388</XCL><XCL>381106</XCL><EDF>4</EDF><ICL>H04M  160</ICL><FSC>381</FSC><FSS>68;684;94;96;102;106;107;111;72;113</FSS><FSC>379</FSC><FSS>388;389;390;395;387</FSS></CLAS>
2016-11-08 21:49:41,114 INFO  [main] TransformerCli - Record: 'US4891837' from /Users/patrick/dev/repos/PatentPublicData/BulkDownloader/download/grants/1990/pftaps19900102_wk01.zip:810
2016-11-08 21:49:41,133 WARN  [main] ClassificationNode - Failed to Parse IPC Classification: 'H04S  300' from : <CLAS><OCL>381 22</OCL><EDF>4</EDF><ICL>H04S  300</ICL><FSC>381</FSC><FSS>17;18;19;20;21;22;23</FSS></CLAS>
2016-11-08 21:49:41,135 INFO  [main] TransformerCli - Record: 'US4891839' from /Users/patrick/dev/repos/PatentPublicData/BulkDownloader/download/grants/1990/pftaps19900102_wk01.zip:811
2016-11-08 21:49:41,180 WARN  [main] ClassificationNode - Failed to Parse IPC Classification: 'H03G  500' from : <CLAS><OCL>351 98</OCL><XCL>333 28T</XCL><EDF>4</EDF><ICL>H03G  500</ICL><FSC>328</FSC><FSS>28 T;28 R</FSS><FSC>381</FSC><FSS>98;103</FSS></CLAS>
2016-11-08 21:49:41,181 INFO  [main] TransformerCli - Record: 'US4891841' from /Users/patrick/dev/repos/PatentPublicData/BulkDownloader/download/grants/1990/pftaps19900102_wk01.zip:812
2016-11-08 21:49:41,190 INFO  [main] TransformerCli - Record: 'US4891843' from /Users/patrick/dev/repos/PatentPublicData/BulkDownloader/download/grants/1990/pftaps19900102_wk01.zip:813
Exception in thread "main" java.util.NoSuchElementException
	at gov.uspto.patent.bulk.DumpFileAps.read(DumpFileAps.java:50)
	at gov.uspto.patent.bulk.DumpFile.next(DumpFile.java:92)
	at gov.uspto.patent.bulk.DumpFile.next(DumpFile.java:23)
	at gov.uspto.patent.TransformerCli.processDumpFile(TransformerCli.java:160)
	at gov.uspto.patent.TransformerCli.process(TransformerCli.java:116)
	at gov.uspto.patent.TransformerCli.main(TransformerCli.java:276)
```

**Comment by bgfeldm** [comment]
Fix checked in.

Good catch on the last record, since greenbook only has startTags the last record would be until the files end.

For the NoSuchElementException, iterators in java often throw it (I guess only when the outer bounds are known, which in this case are not),  I had switched to returning null within the DumpFileXml but didn't reflect the same change within the DumpFileAps.  I just hate passing nulls. 

Thanks again,

Brian
