### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException

### ISSUE THREAD

**Issue by pah32** [USPTO/PatentPublicData#94]
I get the following error when trying to ttransform pftaps19760203_wk05.zip

`2019-11-27 20:19:37,314 WARN  [       main] pftaps19760203_wk05.zip:238:US3935828A ClassificationNode - Failed to Parse locarno IPC Classification: '114' from : <CLAS><OCL>114102</OCL><XCL>73178R</XCL><XCL>114144E</XCL><EDF>2</EDF><ICL>114</ICL><ICL>B63H  904</ICL><ICL>G01C 2112</ICL><FSC>114</FSC><FSS>144 R;114 C;114 E;39;102;105</FSS><FSC>318</FSC><FSS>588</FSS><FSC>73</FSC><FSS>178 R;180;181;186;187;189;182;144</FSS></CLAS>
Exception in thread "main" java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:878)
	at com.google.common.base.Strings.padStart(Strings.java:90)
	at gov.uspto.patent.model.classification.LocarnoClassification.getTree(LocarnoClassification.java:72)
	at gov.uspto.patent.serialize.JsonMapperStream.writeSingleClassificationType(JsonMapperStream.java:700)
	at gov.uspto.patent.serialize.JsonMapperStream.writeClassifications(JsonMapperStream.java:561)
	at gov.uspto.patent.serialize.JsonMapperStream.output(JsonMapperStream.java:145)
	at gov.uspto.patent.serialize.JsonMapperStream.write(JsonMapperStream.java:97)
	at gov.uspto.bulkdata.tools.transformer.TransformerRecordProcessor.writeOutputType(TransformerRecordProcessor.java:142)
	at gov.uspto.bulkdata.tools.transformer.TransformerRecordProcessor.process(TransformerRecordProcessor.java:106)
	at gov.uspto.bulkdata.RecordReader.read(RecordReader.java:195)
	at gov.uspto.bulkdata.RecordReader.read(RecordReader.java:122)
	at gov.uspto.bulkdata.RecordReader.readDirectory(RecordReader.java:145)
	at gov.uspto.bulkdata.RecordReader.read(RecordReader.java:92)
	at gov.uspto.bulkdata.RecordReader.read(RecordReader.java:85)
	at gov.uspto.bulkdata.RecordReader.read(RecordReader.java:43)
	at gov.uspto.bulkdata.cli.Transformer.exec(Transformer.java:77)
	at gov.uspto.bulkdata.cli.Transformer.main(Transformer.java:115)`

**Comment by bgfeldm** [comment]
Closing see #96
