### ISSUE TITLE
null pointer exception when transforming pftaps file to a bulk of jsons

### ISSUE THREAD

**Issue by sotnikov-s** [USPTO/PatentPublicData#96]
The exception is being thrown at a concrete file point. In this case (file pftaps19760203_wk05.zip), it's 238-th (see **--skip** and **--limit** flags) patent info:
```text
java -jar transformer.jar -f=pftaps19760203_wk05.zip --type=json --outDir=. --outBulk=false --prettyPrint=true --skip=237 --limit=1
log4j:WARN No appenders could be found for logger (gov.uspto.patent.PatentDocFormatDetect).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Exception in thread "main" java.lang.NullPointerException
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:878)
        at com.google.common.base.Strings.padStart(Strings.java:90)
        at gov.uspto.patent.model.classification.LocarnoClassification.getTree(LocarnoClassification.java:72)
        at gov.uspto.patent.serialize.JsonMapperStream.writeSingleClassificationType(JsonMapperStream.java:700)
        at gov.uspto.patent.serialize.JsonMapperStream.writeClassifications(JsonMapperStream.java:561)
        at gov.uspto.patent.serialize.JsonMapperStream.output(JsonMapperStream.java:145)
        at gov.uspto.patent.serialize.JsonMapperStream.write(JsonMapperStream.java:97)
        at gov.uspto.bulkdata.tools.transformer.TransformerRecordProcessor.writeOutputType(TransformerRecordProcessor.java:142)
        at gov.uspto.bulkdata.tools.transformer.TransformerRecordProcessor.process(TransformerRecordProcessor.java:90)
        at gov.uspto.bulkdata.RecordReader.read(RecordReader.java:195)
        at gov.uspto.bulkdata.RecordReader.read(RecordReader.java:122)
        at gov.uspto.bulkdata.RecordReader.read(RecordReader.java:85)
        at gov.uspto.bulkdata.RecordReader.read(RecordReader.java:43)
        at gov.uspto.bulkdata.cli.Transformer.exec(Transformer.java:77)
        at gov.uspto.bulkdata.cli.Transformer.main(Transformer.java:115)
```

Wherein 236 and 238 documents are being parsed successfully. 
The same error happens also when parsing 373-rd patent in the same file:
```text
java -jar transformer.jar -f=pftaps19760203_wk05.zip --type=json --outDir=. --outBulk=false --prettyPrint=true --skip=372 --limit=1
log4j:WARN No appenders could be found for logger (gov.uspto.patent.PatentDocFormatDetect).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Exception in thread "main" java.lang.NullPointerException
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:878)
        at com.google.common.base.Strings.padStart(Strings.java:90)
        at gov.uspto.patent.model.classification.LocarnoClassification.getTree(LocarnoClassification.java:72)
        at gov.uspto.patent.serialize.JsonMapperStream.writeSingleClassificationType(JsonMapperStream.java:700)
        at gov.uspto.patent.serialize.JsonMapperStream.writeClassifications(JsonMapperStream.java:561)
        at gov.uspto.patent.serialize.JsonMapperStream.output(JsonMapperStream.java:145)
        at gov.uspto.patent.serialize.JsonMapperStream.write(JsonMapperStream.java:97)
        at gov.uspto.bulkdata.tools.transformer.TransformerRecordProcessor.writeOutputType(TransformerRecordProcessor.java:142)
        at gov.uspto.bulkdata.tools.transformer.TransformerRecordProcessor.process(TransformerRecordProcessor.java:90)
        at gov.uspto.bulkdata.RecordReader.read(RecordReader.java:195)
        at gov.uspto.bulkdata.RecordReader.read(RecordReader.java:122)
        at gov.uspto.bulkdata.RecordReader.read(RecordReader.java:85)
        at gov.uspto.bulkdata.RecordReader.read(RecordReader.java:43)
        at gov.uspto.bulkdata.cli.Transformer.exec(Transformer.java:77)
        at gov.uspto.bulkdata.cli.Transformer.main(Transformer.java:115)
```

Sure there are more such cases.

**Comment by bgfeldm** [comment]
I am not able to reproduce the error. Instead the software throws an warning for the record. The code was last edited July 2019, have you updated and rebuilt since then?

2019-12-23 08:18:40,074 INFO  [       main] pftaps19760203_wk05.zip:200:US3935790A RecordReader - ... mark pftaps19760203_wk05.zip:200
2019-12-23 08:18:40,445 WARN  [       main] pftaps19760203_wk05.zip:238:US3935828A ClassificationNode - Failed to Parse locarno IPC Classification: '114' from : <CLAS><OCL>114102</OCL><XCL>73178R</XCL><XCL>114144E</XCL><EDF>2</EDF><ICL>114</ICL><ICL>B63H  904</ICL><ICL>G01C 2112</ICL><FSC>114</FSC><FSS>144 R;114 C;114 E;39;102;105</FSS><FSC>318</FSC><FSS>588</FSS><FSC>73</FSC><FSS>178 R;180;181;186;187;189;182;144</FSS></CLAS>
2019-12-23 08:18:41,042 INFO  [       main] pftaps19760203_wk05.zip:300:US3935890A RecordReader - ... mark pftaps19760203_wk05.zip:300
2019-12-23 08:18:41,662 WARN  [       main] pftaps19760203_wk05.zip:373:US3935963A ClassificationNode - Failed to Parse locarno IPC Classification: '222' from : <CLAS><OCL>220315</OCL><XCL>215221</XCL><XCL>222153</XCL><EDF>2</EDF><ICL>B65D 4500</ICL><ICL>222</ICL><FSC>215</FSC><FSS>216;221;9</FSS><FSC>220</FSC><FSS>315</FSS></CLAS>
2019-12-23 08:18:41,872 INFO  [       main] pftaps19760203_wk05.zip:400:US3935990A RecordReader - ... mark pftaps19760203_wk05.zip:400

**Comment by sotnikov-s** [comment]
I pulled the repo a week ago and use the master branch as the source. and I just retried it with pulling from master and build the .jar anew. could you please affirm my building steps are right?

1. pull repo
2. cd to $REPO_ROOT/BulkDownloader/
3. run `mvn package`
4. got an error:
```text
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:3.1.1:single (default) on project BulkDownloader: Error reading assemblies: Error locating assembly descriptor: resources/assembly/bin.xml
```
5. copy $REPO_ROOT/resources/assembly/bin.xml to $REPO_ROOT/BulkDownloader/ to avoid that error
6. run `mvn package` again with success result
7. `cd BulkDownloader/target/dependency-jars`
8. unzip all jars and create a new dependency.jar file containing all dependency folders:
```text
mkdir dependencies
unzip \*.jar -d dependencies/
cd dependencies
jar cf dependency.jar *
```
9. `cd BulkDownloader/target/classes`
10. create a manifest file with the following content:
```text
Manifest-Version: 1.0
Created-By: 1.7.0_06 (Oracle Corporation)
Main-Class: gov.uspto.bulkdata.cli.Transformer
Class-Path: dependency.jar
```
11. run `jar cfm transformer.jar manifest.txt gov/*`
12. put together transformer.jar and dependency.jar and use the transformer.jar as following:
`java -jar transformer.jar -f=pftaps19760203_wk05.zip --type=json --outDir=. --outBulk=false --prettyPrint=true`

**Comment by bgfeldm** [comment]
After pulling the repo run "maven clean package" from the top level directory (not from within BulkDownloader).  If test are failing, you can skip test with "maven clean package -DskipTests=true".
If the maven build is successful a zip file should be created under target; "./target/PatentPublicData-0.0.1-SNAPSHOT-*.zip".

**Comment by sotnikov-s** [comment]
> If the maven build is successful a zip file should be created under target; "./target/PatentPublicData-0.0.1-SNAPSHOT-*.zip".

Could you please explain what you meant here? The build was successful. How can I now make a proper .jar file?
